apiVersion: v2
name: rancher-namespace-filter
description: Filtered namespace list for Rancher tenants
type: application
version: 0.2.0
appVersion: 0.2.0
kubeVersion: '>=1.27.0-0'
home: https://github.com/evil8io/rancher-namespace-filter
sources:
  - https://github.com/evil8io/rancher-namespace-filter
