{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "rancher-namespace-filter.fullname" . }}
  labels:
    {{- include "rancher-namespace-filter.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        {{- range .Values.httpRoute.clusterIds }}
        - path:
            type: Exact
            value: /k8s/clusters/{{ . }}/api/v1/namespaces
          method: GET
        - path:
            type: Exact
            value: /k8s/clusters/{{ . }}/apis/authorization.k8s.io/v1/selfsubjectaccessreviews
          method: POST
        {{- end }}
      backendRefs:
        - name: {{ include "rancher-namespace-filter.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
