{{- if and (not .Values.token.existingSecret) .Values.token.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher-namespace-filter.tokenSecretName" . }}
  labels:
    {{- include "rancher-namespace-filter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.token.key }}: {{ .Values.token.value | quote }}
{{- end }}
